server:
  port: 8888
  
user:
  name: user
  password: password
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wubet/pluralsignt-spring-cloudconfig-wa-tollsa
          
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/wubet/pluralsignt-spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'
    management:
      endpoints:
        web:
          exposure:
            include: "*"
          